---
# tasks file for netplan
- name: Template a file to /etc/netplan/00-ansible-netplan.yaml
  ansible.builtin.template:
    src: netplan.j2
    dest: /etc/netplan/00-ansible-netplan.yaml

- name: Check in default netplan exists
  ansible.builtin.stat:
    path: /etc/netplan/00-installer-config.yaml
  register: netplan

- block:
    - name: Move default netplan file to backup
      copy:
        remote_src: yes
        src: /etc/netplan/00-installer-config.yaml 
        dest: /etc/netplan/00-installer-config.yaml.bak

    - name: Remove old netplan file
      file:
        path: /etc/netplan/00-installer-config.yaml
        state: absent
  when: netplan.stat.exists

- name: Apply netplan config    
  command: netplan apply