---
# tasks file for netplan
- name: Check if default netplan exists
  ansible.builtin.stat:
    path: /etc/netplan/00-installer-config.yaml
  register: default_netplan

- block:
    - name: Move default netplan file to backup
      copy:
        remote_src: yes
        src: /etc/netplan/00-installer-config.yaml 
        dest: /etc/netplan/00-installer-config.yaml.bak

    - name: Remove old netplan file
      file:
        path: /etc/netplan/00-installer-config.yaml
        state: absent
  when: default_netplan.stat.exists

- name: Check if new netplan exists
  ansible.builtin.stat:
    path: /etc/netplan/00-installer-config.yaml
  register: new_netplan
  
- block:
    - name: Template a file to /etc/netplan/00-ansible-netplan.yaml
      ansible.builtin.template:
        src: netplan.j2
        dest: /etc/netplan/00-ansible-netplan.yaml

    - name: Apply netplan config    
      command: netplan apply
  when: not new_netplan.stat.exists