---
# tasks file for ssh
- name: Ensure group "nopwsudo" exists
  ansible.builtin.group:
    name: nopwsudo
    state: present

- name: Add the user ansible with a bash shell, appending the group nopwsudo to the user's groups
  ansible.builtin.user:
    name: ansible
    shell: /bin/bash
    groups: nopwsudo
    append: yes

- name: copy SSH key for user rspoon
  copy: 
    src: "{{ item }}"
    dest: /home/rspoon/.ssh/
    owner: rspoon
    group: rspoon
    mode: '0644'
  with_fileglob:
    - "/home/rspoon/.ssh/id_*"

- name: Copy SSH id for user ansible  
  ansible.posix.authorized_key:
    user: ansible
    state: present
    key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"

- name: Ensure passwordless sudo rule exists in /etc/sudoers
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: '^%sudo   ALL=(ALL:ALL) ALL'
    insertafter: '^%sudo   ALL=(ALL:ALL) ALL'
    line: >
      # Allow members of group nopwsudo to execute any command
      %nopwsudo         ALL = (ALL) NOPASSWD: ALL
    state: present


